const PROJECTS = [
  {
    id: '01-blackhorse',
    name: 'BlackHorse',
    tag: 'B2B Platform',
    summary: 'Wholesale delivery platform for supermarkets, suppliers, and drivers with real-time orders and group purchasing.',
    stack: ['Node.js', 'MongoDB', 'Socket.IO', 'Flutter'],
    thumb: '01-blackhorse/screenshots/01-admin-login.png',
    readme: 'github-readmes/blackhorse/README.md',
    caseStudy: 'case-studies/blackhorse.md',
    arch: 'docs/architecture/blackhorse.md',
    api: 'docs/api/blackhorse.md',
    repo: 'https://github.com/Abdelrahman1203/blackhorse-platform',
  },
  {
    id: '02-real-estate-all-stars',
    name: 'Real Estate All-Stars',
    tag: 'Contest Platform',
    summary: 'Bilingual broker talent competition with video uploads, voting, and Fawaterak payment integration.',
    stack: ['Laravel 10', 'MySQL', 'Tailwind', 'Fawaterak'],
    thumb: '02-real-estate-all-stars/screenshots/01-home-register.png',
    readme: 'github-readmes/real-estate-all-stars/README.md',
    caseStudy: 'case-studies/real-estate-all-stars.md',
    arch: 'docs/architecture/real-estate-all-stars.md',
    api: 'docs/api/real-estate-all-stars.md',
    repo: 'https://github.com/Abdelrahman1203/real-estate-all-stars',
  },
  {
    id: '03-erp-arabia',
    name: 'ERP Arabia',
    tag: 'Warehouse ERP',
    summary: 'Multi-branch warehouse ERP with purchases, transfers, stock adjustments, and Arabic RTL reports.',
    stack: ['Laravel', 'Vue 3', 'MongoDB', 'Redis'],
    thumb: '03-erp-arabia/screenshots/02-dashboard.png',
    readme: 'github-readmes/erp-arabia/README.md',
    caseStudy: 'case-studies/erp-arabia.md',
    arch: 'docs/architecture/erp-arabia.md',
    api: 'docs/api/erp-arabia.md',
    repo: 'https://github.com/Abdelrahman1203/erp-arabia',
  },
  {
    id: '04-boatbnb-erp-monorepo',
    name: 'BoatBnB + ERP',
    tag: 'Monorepo',
    summary: 'Laravel 12 monorepo combining warehouse ERP and boat rental marketplace with Stripe payments.',
    stack: ['Laravel 12', 'Vue 3', 'Stripe', 'AWS S3'],
    thumb: '04-boatbnb-erp-monorepo/screenshots/01-welcome-page.png',
    readme: 'github-readmes/boatbnb-erp/README.md',
    caseStudy: 'case-studies/boatbnb-erp.md',
    arch: 'docs/architecture/boatbnb-erp.md',
    api: 'docs/api/boatbnb-erp.md',
    repo: 'https://github.com/Abdelrahman1203/boatbnb-erp-monorepo',
  },
  {
    id: '05-easternco-law-erp',
    name: 'Eastern & Co',
    tag: 'Law Firm ERP',
    summary: 'Modular ERP/CRM for law firm: CRM, legal tasks, HR, finance, and bilingual public website.',
    stack: ['Laravel 10', 'Modules', 'Spatie', 'Twilio'],
    thumb: '05-easternco-law-erp/screenshots/01-admin-login.png',
    readme: 'github-readmes/easternco-law-erp/README.md',
    caseStudy: 'case-studies/easternco-law-erp.md',
    arch: 'docs/architecture/easternco-law-erp.md',
    api: 'docs/api/easternco-law-erp.md',
    repo: 'https://github.com/Abdelrahman1203/easternco-law-erp',
  },
  {
    id: '06-estshary-admin',
    name: 'Estshary Admin',
    tag: 'Healthcare',
    summary: 'Healthcare admin panel with doctor/clinic management, AI chatbot, and mobile JWT APIs.',
    stack: ['Laravel 10', 'JWT', 'OpenAI', 'Firebase'],
    thumb: '06-estshary-admin/screenshots/01-login.png',
    readme: 'github-readmes/estshary-admin/README.md',
    caseStudy: 'case-studies/estshary-admin.md',
    arch: 'docs/architecture/estshary-admin.md',
    api: 'docs/api/estshary-admin.md',
    repo: 'https://github.com/Abdelrahman1203/estshary-admin',
  },
  {
    id: '07-estshary-patient-site',
    name: 'Estshary Patient',
    tag: 'Healthcare',
    summary: 'Public patient portal for doctor search, appointment booking, and medical services.',
    stack: ['Laravel 10', 'Blade', 'MySQL', 'AJAX'],
    thumb: '07-estshary-patient-site/screenshots/01-homepage.png',
    readme: 'github-readmes/estshary-patient/README.md',
    caseStudy: 'case-studies/estshary-patient.md',
    arch: 'docs/architecture/estshary-admin.md',
    api: 'docs/api/estshary-admin.md',
    repo: 'https://github.com/Abdelrahman1203/estshary-patient',
  },
  {
    id: '08-hr-system',
    name: 'HR System',
    tag: 'HR & Payroll',
    summary: 'HR platform with ZKTeco attendance, configurable payroll rules, leave management, and bilingual UI.',
    stack: ['Laravel 12', 'React 19', 'MongoDB'],
    thumb: '08-hr-system/screenshots/02-dashboard.png',
    readme: 'github-readmes/hr-system/README.md',
    caseStudy: 'case-studies/hr-system.md',
    arch: 'docs/architecture/hr-system.md',
    api: 'docs/api/hr-system.md',
    repo: 'https://github.com/Abdelrahmanwaleed930/hr-system',
  },
  {
    id: '09-trc-referrals',
    name: 'TRC Referrals',
    tag: 'Real Estate',
    summary: 'Real estate referral platform with admin pipeline, commission wallets, and mobile property API.',
    stack: ['Laravel 10', 'MySQL', 'Sanctum', 'FCM'],
    thumb: '09-trc-referrals/screenshots/01-admin-login.png',
    readme: 'github-readmes/trc-referrals/README.md',
    caseStudy: 'case-studies/trc-referrals.md',
    arch: 'docs/architecture/trc-referrals.md',
    api: 'docs/api/trc-referrals.md',
    repo: 'https://github.com/Abdelrahman1203/trc-referrals',
  },
];

const CASE_STUDIES = [
  {
    title: 'BlackHorse — B2B Delivery at Scale',
    impact: '240+ API endpoints · Real-time order tracking',
    summary: 'Replaced manual phone-based wholesale ordering with a multi-role platform serving suppliers, stores, and drivers.',
    link: 'case-studies/blackhorse.md',
  },
  {
    title: 'ERP Arabia — Multi-Branch Inventory',
    impact: '10+ exportable reports · Arabic RTL support',
    summary: 'Unified warehouse operations across branches with purchase approval workflows and inter-warehouse transfers.',
    link: 'case-studies/erp-arabia.md',
  },
  {
    title: 'HR System — Automated Payroll Rules',
    impact: '13+ admin modules · ZKTeco biometric sync',
    summary: 'Eliminated manual attendance spreadsheets with configurable deduction/overtime rule engine and payroll export.',
    link: 'case-studies/hr-system.md',
  },
  {
    title: 'Real Estate All-Stars — Contest Platform',
    impact: 'Bilingual EN/AR · Fawaterak payments',
    summary: 'Launched regional broker competition with video submissions, daily voting limits, and paid vote packages.',
    link: 'case-studies/real-estate-all-stars.md',
  },
  {
    title: 'TRC — Referral Commission Pipeline',
    impact: 'Multi-stage workflows · Wallet & FCM',
    summary: 'Digitized real estate referral tracking from lead to commission payout with admin pipeline and mobile API.',
    link: 'case-studies/trc-referrals.md',
  },
  {
    title: 'Estshary — Healthcare Booking Ecosystem',
    impact: '118+ migrations · AI doctor matching',
    summary: 'Connected admin panel, patient website, and mobile APIs for end-to-end appointment booking.',
    link: 'case-studies/estshary-admin.md',
  },
];
