const PROJECTS = [
  {
    id: '01-blackhorse',
    name: 'BlackHorse',
    tag: 'B2B Platform',
    summary: 'Wholesale delivery platform for supermarkets, suppliers, and drivers with real-time orders and group purchasing.',
    stack: ['Node.js', 'MongoDB', 'Socket.IO', 'Flutter'],
    thumb: '01-blackhorse/screenshots/01-admin-login.png',
    readme: 'github-readmes/blackhorse/README.md',
    caseStudy: 'case-studies/blackhorse.md',
    arch: 'docs/architecture/blackhorse.md',
    api: 'docs/api/blackhorse.md',
    repo: 'https://github.com/Abdelrahman1203/blackhorse-platform',
  },
  {
    id: '02-real-estate-all-stars',
    name: 'Real Estate All-Stars',
    tag: 'Contest Platform',
    summary: 'Bilingual broker talent competition with video uploads, voting, and Fawaterak payment integration.',
    stack: ['Laravel 10', 'MySQL', 'Tailwind', 'Fawaterak'],
    thumb: '02-real-estate-all-stars/screenshots/01-home-register.png',
    readme: 'github-readmes/real-estate-all-stars/README.md',
    caseStudy: 'case-studies/real-estate-all-stars.md',
    arch: 'docs/architecture/real-estate-all-stars.md',
    api: 'docs/api/real-estate-all-stars.md',
    repo: 'https://github.com/Abdelrahman1203/real-estate-all-stars',
  },
  {
    id: '03-erp-arabia',
    name: 'ERP Arabia',
    tag: 'Warehouse ERP',
    summary: 'Multi-branch warehouse ERP with purchases, transfers, stock adjustments, and Arabic RTL reports.',
    stack: ['Laravel', 'Vue 3', 'MongoDB', 'Redis'],
    thumb: '03-erp-arabia/screenshots/02-dashboard.png',
    readme: 'github-readmes/erp-arabia/README.md',
    caseStudy: 'case-studies/erp-arabia.md',
    arch: 'docs/architecture/erp-arabia.md',
    api: 'docs/api/erp-arabia.md',
    repo: 'https://github.com/Abdelrahman1203/erp-arabia',
  },
  {
    id: '04-boatbnb-erp-monorepo',
    name: 'BoatBnB + ERP',
    tag: 'Travel & Marine',
    summary: 'Multi-platform boat rental ecosystem with customer, provider, agency, guest, and admin applications featuring real-time chat, GPS tracking, multilingual support, Stripe payments, and an integrated ERP system.',
    stack: ['Laravel 12', 'Vue 3', 'Stripe', 'Agora', 'MongoDB', 'AWS S3'],
    meta: {
      industry: 'Travel & Marine Services',
      role: 'Sole Full-Stack Engineer & Solutions Architect',
      duration: 'Jul 2025 – Jan 2026',
      teamSize: '1',
      platforms: 'Web Admin, Provider Portal, Customer App, Agency App',
      languages: '10',
      soleDeveloper: 'Sole developer responsible for business analysis, architecture, frontend, backend, infrastructure, testing, deployment, and maintenance.',
      features: [
        'Boat discovery and search', 'GPS tracking', 'Booking and scheduling', 'Stripe payments',
        'Referral system', 'Real-time chat with Agora', 'Multi-language support', 'Provider onboarding',
        'Commission and payout management', 'Notifications', 'Admin ERP dashboard', 'Analytics and reporting',
      ],
    },
    thumb: '04-boatbnb-erp-monorepo/screenshots/11-mobile-home-search.png',
    readme: 'github-readmes/boatbnb-erp/README.md',
    caseStudy: 'case-studies/boatbnb-erp.md',
    arch: 'docs/architecture/boatbnb-erp.md',
    api: 'docs/api/boatbnb-erp.md',
    repo: 'https://github.com/Abdelrahman1203/boatbnb-erp-monorepo',
  },
  {
    id: '05-easternco-law-erp',
    name: 'Eastern & Co',
    tag: 'Law Firm ERP',
    summary: 'Modular ERP/CRM for law firm: CRM, legal tasks, HR, finance, and bilingual public website.',
    stack: ['Laravel 10', 'Modules', 'Spatie', 'Twilio'],
    thumb: '05-easternco-law-erp/screenshots/01-admin-login.png',
    readme: 'github-readmes/easternco-law-erp/README.md',
    caseStudy: 'case-studies/easternco-law-erp.md',
    arch: 'docs/architecture/easternco-law-erp.md',
    api: 'docs/api/easternco-law-erp.md',
    repo: 'https://github.com/Abdelrahman1203/easternco-law-erp',
  },
  {
    id: '06-estshary-admin',
    name: 'Estshary Admin',
    tag: 'Healthcare',
    summary: 'Healthcare admin panel with doctor/clinic management, AI chatbot, and mobile JWT APIs.',
    stack: ['Laravel 10', 'JWT', 'OpenAI', 'Firebase'],
    thumb: '06-estshary-admin/screenshots/01-login.png',
    readme: 'github-readmes/estshary-admin/README.md',
    caseStudy: 'case-studies/estshary-admin.md',
    arch: 'docs/architecture/estshary-admin.md',
    api: 'docs/api/estshary-admin.md',
    repo: 'https://github.com/Abdelrahman1203/estshary-admin',
  },
  {
    id: '07-estshary-patient-site',
    name: 'Estshary Patient',
    tag: 'Healthcare',
    summary: 'Public patient portal for doctor search, appointment booking, and medical services.',
    stack: ['Laravel 10', 'Blade', 'MySQL', 'AJAX'],
    thumb: '07-estshary-patient-site/screenshots/01-homepage.png',
    readme: 'github-readmes/estshary-patient/README.md',
    caseStudy: 'case-studies/estshary-patient.md',
    arch: 'docs/architecture/estshary-admin.md',
    api: 'docs/api/estshary-admin.md',
    repo: 'https://github.com/Abdelrahman1203/estshary-patient',
  },
  {
    id: '08-hr-system',
    name: 'HR System',
    tag: 'HR & Payroll',
    summary: 'HR platform with ZKTeco attendance, configurable payroll rules, leave management, and bilingual UI.',
    stack: ['Laravel 12', 'React 19', 'MongoDB'],
    thumb: '08-hr-system/screenshots/02-dashboard.png',
    readme: 'github-readmes/hr-system/README.md',
    caseStudy: 'case-studies/hr-system.md',
    arch: 'docs/architecture/hr-system.md',
    api: 'docs/api/hr-system.md',
    repo: 'https://github.com/Abdelrahman1203/hr-system-docs',
  },
  {
    id: '09-trc-referrals',
    name: 'TRC Referrals',
    tag: 'Real Estate',
    summary: 'Real estate referral platform with admin pipeline, commission wallets, and mobile property API.',
    stack: ['Laravel 10', 'MySQL', 'Sanctum', 'FCM'],
    thumb: '09-trc-referrals/screenshots/01-admin-login.png',
    readme: 'github-readmes/trc-referrals/README.md',
    caseStudy: 'case-studies/trc-referrals.md',
    arch: 'docs/architecture/trc-referrals.md',
    api: 'docs/api/trc-referrals.md',
    repo: 'https://github.com/Abdelrahman1203/trc-referrals',
  },
  {
    id: '10-harvest-british-college',
    name: 'Harvest British College',
    tag: 'Education ERP',
    summary: 'Full education ERP: CRM leads, class scheduling, payments, instructor & student portals, bilingual website — live at harvestcollege.co.uk.',
    stack: ['Laravel 10', 'Livewire', 'Modules', 'Twilio'],
    meta: {
      industry: 'Education',
      role: 'Software Developer',
      duration: 'Jul 2024 – Jun 2025',
      live: 'harvestcollege.co.uk',
      soleDeveloper: 'Sole developer responsible for business analysis, architecture, frontend, backend, infrastructure, testing, deployment, and maintenance.',
    },
    thumb: '10-harvest-british-college/screenshots/11-admin-login.png',
    readme: 'github-readmes/harvest-british-college/README.md',
    caseStudy: 'case-studies/harvest-british-college.md',
    arch: 'docs/architecture/harvest-british-college.md',
    api: 'docs/api/harvest-british-college.md',
    repo: 'https://github.com/Abdelrahman1203/harvest-british-college',
  },
];

function renderProjectMeta(p) {
  if (!p.meta) return '';
  const m = p.meta;
  const rows = [];
  if (m.industry) rows.push(`<span><strong>Industry:</strong> ${m.industry}</span>`);
  if (m.role) rows.push(`<span><strong>Role:</strong> ${m.role}</span>`);
  if (m.duration) rows.push(`<span><strong>Duration:</strong> ${m.duration}</span>`);
  if (m.teamSize) rows.push(`<span><strong>Team:</strong> ${m.teamSize}</span>`);
  if (m.platforms) rows.push(`<span><strong>Platforms:</strong> ${m.platforms}</span>`);
  if (m.languages) rows.push(`<span><strong>Languages:</strong> ${m.languages}</span>`);
  if (m.live) rows.push(`<span><strong>Live:</strong> ${m.live}</span>`);
  let html = `<div class="project-meta">${rows.join('')}</div>`;
  if (m.soleDeveloper) html += `<p class="project-note">${m.soleDeveloper}</p>`;
  if (m.features?.length) {
    html += `<ul class="project-features">${m.features.map((f) => `<li>${f}</li>`).join('')}</ul>`;
  }
  return html;
}

const CASE_STUDIES = [
  {
    title: 'BlackHorse — B2B Delivery at Scale',
    impact: '240+ API endpoints · Real-time order tracking',
    summary: 'Replaced manual phone-based wholesale ordering with a multi-role platform serving suppliers, stores, and drivers.',
    link: 'case-studies/blackhorse.md',
    projectId: '01-blackhorse',
  },
  {
    title: 'ERP Arabia — Multi-Branch Inventory',
    impact: '10+ exportable reports · Arabic RTL support',
    summary: 'Unified warehouse operations across branches with purchase approval workflows and inter-warehouse transfers.',
    link: 'case-studies/erp-arabia.md',
    projectId: '03-erp-arabia',
  },
  {
    title: 'HR System — Automated Payroll Rules',
    impact: '13+ admin modules · ZKTeco biometric sync',
    summary: 'Eliminated manual attendance spreadsheets with configurable deduction/overtime rule engine and payroll export.',
    link: 'case-studies/hr-system.md',
    projectId: '08-hr-system',
  },
  {
    title: 'Real Estate All-Stars — Contest Platform',
    impact: 'Bilingual EN/AR · Fawaterak payments',
    summary: 'Launched regional broker competition with video submissions, daily voting limits, and paid vote packages.',
    link: 'case-studies/real-estate-all-stars.md',
    projectId: '02-real-estate-all-stars',
  },
  {
    title: 'TRC — Referral Commission Pipeline',
    impact: 'Multi-stage workflows · Wallet & FCM',
    summary: 'Digitized real estate referral tracking from lead to commission payout with admin pipeline and mobile API.',
    link: 'case-studies/trc-referrals.md',
    projectId: '09-trc-referrals',
  },
  {
    title: 'Estshary — Healthcare Booking Ecosystem',
    impact: '118+ migrations · AI doctor matching',
    summary: 'Connected admin panel, patient website, and mobile APIs for end-to-end appointment booking.',
    link: 'case-studies/estshary-admin.md',
    projectId: '06-estshary-admin',
  },
  {
    title: 'Harvest British College — Education ERP',
    impact: '3 portals · 20+ reports · Live at harvestcollege.co.uk',
    summary: 'Unified CRM, class operations, payments, and multi-portal access for admin, instructors, and students.',
    link: 'case-studies/harvest-british-college.md',
    projectId: '10-harvest-british-college',
  },
  {
    title: 'BoatBnB + ERP — Multi-Platform Boat Rental Marketplace',
    impact: 'Sole developer · 5 apps · 10 languages · GPS + Stripe + Agora',
    summary: 'Multi-platform boat rental ecosystem with customer, provider, agency, guest, and admin applications featuring real-time chat, GPS tracking, Stripe payments, and integrated ERP.',
    link: 'case-studies/boatbnb-erp.md',
    projectId: '04-boatbnb-erp-monorepo',
  },
];
